//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPPK_I7
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grad
    {
        public int IDGrad { get; set; }
        public string Naziv { get; set; }
        public string GeoSirina { get; set; }
        public string GeoVisina { get; set; }
    }
}
