//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPPK_I7
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PPPK_ProjektEntities : DbContext
    {
        public PPPK_ProjektEntities()
            : base("name=PPPK_ProjektEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Grad> Grad { get; set; }
        public virtual DbSet<PutniNalog> PutniNalog { get; set; }
        public virtual DbSet<Servis> Servis { get; set; }
        public virtual DbSet<Vozac> Vozac { get; set; }
        public virtual DbSet<Vozilo> Vozilo { get; set; }
    }
}
