//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPPK_I7
{
    using System;
    using System.Collections.Generic;
    
    public partial class PutniNalog
    {
        public int IDPutniNalog { get; set; }
        public int VozacID { get; set; }
        public int VoziloID { get; set; }
        public System.DateTime Datum { get; set; }
        public string Tip { get; set; }
        public string KoordinataA { get; set; }
        public string KoordinataB { get; set; }
        public Nullable<int> PrijedeniKilometri { get; set; }
        public Nullable<int> ProsjecnaBrzina { get; set; }
        public Nullable<int> PotrosenoGorivo { get; set; }
    }
}
