//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPPK_I7
{
    using System;
    using System.Collections.Generic;
    
    public partial class Servis
    {
        public int IDServis { get; set; }
        public int Vozilo { get; set; }
        public int StanjeKilometara { get; set; }
        public string Napomena { get; set; }
        public int IduciServis { get; set; }
        public int Cijena { get; set; }
    }
}
