//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPPK_I7
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vozilo
    {
        public int IDVozilo { get; set; }
        public string Marka { get; set; }
        public string Tip { get; set; }
        public string GodinaProizvodnje { get; set; }
        public string InicijalnoStanjeKilometara { get; set; }
        public string Naziv { get => Marka + " " + Tip; }
    }
}
